apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexthouse
  labels:
    app: nexthouse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexthouse
  template:
    metadata:
      labels:
        app: nexthouse
    spec:
      containers:
      - name: nexthouse
        image: eastshine96/nexthouse:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: nexthouse-config
              key: DB_SERVER
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: nexthouse-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: nexthouse-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: nexthouse-config
              key: DB_PASSWORD
        - name: SERVLET_CONTEXT_PATH
          valueFrom:
            configMapKeyRef:
              name: nexthouse-config
              key: SERVLET_CONTEXT_PATH
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: nexthouse-config
              key: DB_NAME